Repository sweetalert2/sweetalert2, pull requests merged in 2018-03, with the labels that each got.

#973 Optimize gulpfile.js
  .travis.yml
  gulpfile.js
  package.json
  src/sweetalert2.all.js
  src/sweetalert2.js
  utils/package-rollup.js
  yarn.lock
Labels: build & workflow

#994 feature(toasts): change styles to be relative (px -> em)
  src/toasts.scss
Labels: domain: toasts

#972 Add toast close on click (with stipulations)
  src/sweetalert2.js
  test/qunit/toast.js
Labels: domain: toasts, type: feature

#997 Type swal.argsToParams
  sweetalert2.d.ts
Labels: domain: typescript, type: feature

#1022 Override css background image property
  src/sweetalert2.scss
Labels: domain: dom/css

#981 chore(d.ts): improve type safety for 'inputValue' attribute
  sweetalert2.d.ts
Labels: domain: typescript

#1023 Feature/mixin method
  src/sweetalert2.js
  test/qunit/api/api.js
  test/qunit/api/mixins.js
Labels: domain: api, type: feature

#1026 Refactor/extract static methods
  src/globalState.js
  src/staticMethods.js
  src/staticMethods/adaptInputValidator.js
  src/staticMethods/argsToParams.js
  src/staticMethods/close.js
  src/staticMethods/dom.js
  src/staticMethods/mixin.js
  src/staticMethods/queue.js
  src/staticMethods/set-reset-defaults.js
  src/staticMethods/showLoading.js
  src/sweetalert2.js
  src/utils/params.js
Labels: domain: devel, type: refactor

#1025 Feature/input value as promise
  src/sweetalert2.js
  sweetalert2.d.ts
  test/qunit/tests.js
Labels: domain: api, type: feature

#1027 Make release script locale-independent
  package.json
  utils/get-git-status.js
  yarn.lock
Labels: domain: devel

#1034 Refactor/extract instance methods
  src/instanceMethods.js
  src/instanceMethods/enable-disable-elements.js
  src/instanceMethods/getInput.js
  src/instanceMethods/hideLoading.js
  src/instanceMethods/progress-steps.js
  src/instanceMethods/show-set-validation-error.js
  src/sweetalert2.js
Labels: domain: devel, type: refactor

#1036 Feature/object oriented
  README.md
  gulpfile.js
  src/instanceMethods.js
  src/instanceMethods/_main.js
  src/instanceMethods/enable-disable-elements.js
  src/instanceMethods/getInput.js
  src/instanceMethods/hideLoading.js
  src/instanceMethods/progress-steps.js
  src/instanceMethods/show-reset-validation-error.js
  src/staticMethods.js
  src/staticMethods/fire.js
  src/staticMethods/mixin.js
  src/sweetalert2.js
  src/utils/openPopup.js
  src/utils/utils.js
  test/qunit/a11y.js
  test/qunit/api/api.js
  test/qunit/api/mixins.js
  test/qunit/deprecated.js
  test/qunit/helpers.js
  test/qunit/outside-click.js
  test/qunit/tests.js
  test/qunit/toast.js
  test/sandbox.html
Labels: domain: api, domain: devel, type: feature, type: refactor
